# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

require 'google/protobuf'

descriptor_data = "\n\nface.proto\x12\x10\x66\x61\x63\x65_recognition\";\n\x0fRegisterRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"'\n\x0fIdentifyRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\"\\\n\x10IdentifyResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2\xc3\x01\n\x0f\x46\x61\x63\x65Recognition\x12W\n\x0cRegisterFace\x12!.face_recognition.RegisterRequest\x1a\".face_recognition.RegisterResponse\"\x00\x12W\n\x0cIdentifyFace\x12!.face_recognition.IdentifyRequest\x1a\".face_recognition.IdentifyResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module FaceRecognition
  RegisterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('face_recognition.RegisterRequest').msgclass
  RegisterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('face_recognition.RegisterResponse').msgclass
  IdentifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('face_recognition.IdentifyRequest').msgclass
  IdentifyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('face_recognition.IdentifyResponse').msgclass
end
