# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_recognition.proto

require 'google/protobuf'

descriptor_data = "\n\x16\x66\x61\x63\x65_recognition.proto\"3\n\x0e\x41\x64\x64\x46\x61\x63\x65Request\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"E\n\x0f\x41\x64\x64\x46\x61\x63\x65Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x03 \x03(\x01\"%\n\x14RecognizeFaceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"P\n\x15RecognizeFaceResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"3\n\x11TrainModelRequest\x12\x1e\n\x08students\x18\x01 \x03(\x0b\x32\x0c.StudentData\"6\n\x12TrainModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0bStudentData\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x02 \x03(\x01\x32\xbe\x01\n\x0f\x46\x61\x63\x65Recognition\x12\x34\n\x0f\x41\x64\x64\x46\x61\x63\x65\x45ncoding\x12\x0f.AddFaceRequest\x1a\x10.AddFaceResponse\x12>\n\rRecognizeFace\x12\x15.RecognizeFaceRequest\x1a\x16.RecognizeFaceResponse\x12\x35\n\nTrainModel\x12\x12.TrainModelRequest\x1a\x13.TrainModelResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

AddFaceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup('AddFaceRequest').msgclass
AddFaceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('AddFaceResponse').msgclass
RecognizeFaceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup('RecognizeFaceRequest').msgclass
RecognizeFaceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('RecognizeFaceResponse').msgclass
TrainModelRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup('TrainModelRequest').msgclass
TrainModelResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('TrainModelResponse').msgclass
StudentData = Google::Protobuf::DescriptorPool.generated_pool.lookup('StudentData').msgclass
