# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: face_recognition.proto for package ''

require 'grpc'
require 'face_recognition_pb'

module FaceRecognition
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'FaceRecognition'

    rpc :AddFaceEncoding, ::AddFaceRequest, ::AddFaceResponse
    rpc :RecognizeFace, ::RecognizeFaceRequest, ::RecognizeFaceResponse
    rpc :TrainModel, ::TrainModelRequest, ::TrainModelResponse
  end

  Stub = Service.rpc_stub_class
end
